-- CreateTable
CREATE TABLE "Patient" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "socialName" TEXT,
    "cpf" TEXT,
    "rg" TEXT,
    "birthDate" TEXT,
    "sex" TEXT,
    "maritalStatus" TEXT,
    "phone" TEXT,
    "whatsapp" TEXT,
    "email" TEXT,
    "cep" TEXT,
    "address" TEXT,
    "addressNumber" TEXT,
    "neighborhood" TEXT,
    "city" TEXT,
    "state" TEXT,
    "emergencyContact" TEXT,
    "emergencyPhone" TEXT,
    "bloodType" TEXT,
    "allergies" TEXT,
    "chronicDiseases" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Consultation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "patientId" TEXT NOT NULL,
    "audioPath" TEXT,
    "transcript" TEXT,
    "transcriptStructured" TEXT,
    "chiefComplaint" TEXT,
    "hda" TEXT,
    "symptomStart" TEXT,
    "symptomIntensity" TEXT,
    "symptoms" TEXT,
    "improvingFactors" TEXT,
    "worseningFactors" TEXT,
    "previousDiseases" TEXT,
    "surgeries" TEXT,
    "hospitalizations" TEXT,
    "allergiesDetails" TEXT,
    "currentMedications" TEXT,
    "familyHistory" TEXT,
    "smoking" TEXT,
    "alcohol" TEXT,
    "physicalActivity" TEXT,
    "sleep" TEXT,
    "diet" TEXT,
    "drugs" TEXT,
    "occupation" TEXT,
    "systemsReview" TEXT,
    "vitalSigns" TEXT,
    "weight" REAL,
    "height" REAL,
    "bmi" REAL,
    "generalState" TEXT,
    "physicalExam" TEXT,
    "mainHypothesis" TEXT,
    "differentials" TEXT,
    "confirmedDiagnosis" TEXT,
    "cid" TEXT,
    "therapeuticPlan" TEXT,
    "orientations" TEXT,
    "referrals" TEXT,
    "followUpDate" TEXT,
    "subjective" TEXT,
    "objective" TEXT,
    "assessment" TEXT,
    "plan" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Consultation_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
